accepted = [
   "MIT",
    "ISC",
    "Apache-2.0",
    "MPL-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "OpenSSL",
    "CDLA-Permissive-2.0",
    "Zlib",
    "BSL-1.0",
]
workarounds = ["ring"]
no-clearly-defined = true
